import {useCallback, useEffect, useRef, useState} from 'react';
import {api, date, isDemoMode, riskNames, Row} from './api';
import './admin-panel.css';

type Props={settings:Row;user:Row;status:Row;onRefresh:()=>Promise<void>};
const modes:Record<string,string>={rules:'Правила',http:'Внешний сервис',shadow:'Теневой режим',ensemble:'Ансамбль',plugin:'Плагин'};
const metric=(value:unknown,factor=1,digits=3)=>typeof value==='number'&&Number.isFinite(value)?(value*factor).toLocaleString('ru-RU',{maximumFractionDigits:digits}):'Нет данных';
const errorText=(error:unknown)=>error instanceof Error?error.message:'Не удалось выполнить запрос. Повторите попытку.';

export function AdminPanel({settings,user,status,onRefresh}:Props){
 const [models,setModels]=useState<Row[]>([]),[audit,setAudit]=useState<Row[]>([]);
 const [loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[saveError,setSaveError]=useState(''),[notice,setNotice]=useState('');
 const [busy,setBusy]=useState(false),[mode,setMode]=useState(settings.ml_mode??'');
 const [thresholds,setThresholds]=useState<Record<string,string>>(()=>Object.fromEntries(['low','medium','high'].map(k=>[k,String(settings.risk_thresholds?.[k]??'')])));
 const dirty=useRef(false),locked=useRef(false),request=useRef(0);
 useEffect(()=>{if(!dirty.current){setMode(settings.ml_mode??'');setThresholds(Object.fromEntries(['low','medium','high'].map(k=>[k,String(settings.risk_thresholds?.[k]??'')])))}},[settings]);
 const load=useCallback(async()=>{const current=++request.current;setLoading(true);setLoadError('');try{const [m,a]=await Promise.all([api('/ml/models'),user.role==='admin'?api('/admin/audit'):Promise.resolve({items:[]})]);if(current===request.current){setModels(Array.isArray(m)?m:[]);setAudit(Array.isArray(a.items)?a.items:[])}}catch(error){if(current===request.current)setLoadError(errorText(error))}finally{if(current===request.current)setLoading(false)}},[user.role]);
 useEffect(()=>{void load();return()=>{request.current++}},[load]);
 async function save(task:()=>Promise<unknown>,message:string){if(locked.current)return;locked.current=true;setBusy(true);setSaveError('');setNotice('');try{await task();dirty.current=false;await onRefresh();await load();setNotice(message)}catch(error){setSaveError(errorText(error))}finally{locked.current=false;setBusy(false)}}
 function saveThresholds(){const values=Object.fromEntries(Object.entries(thresholds).map(([k,v])=>[k,Number(v)]));if(Object.values(thresholds).some(v=>!v.trim())||!Object.values(values).every(Number.isFinite)||!(0<=values.low&&values.low<values.medium&&values.medium<values.high&&values.high<=1)){setSaveError('Введите три порога от 0 до 1: низкий < повышенный < высокий.');return}void save(()=>api('/settings',{risk_thresholds:values},'PUT'),isDemoMode?'Пороги сохранены только в локальном демо.':'Пороги сохранены.');}
 return <section className="admin-console" aria-labelledby="admin-title"><div className="ac-heading"><div><span>УПРАВЛЕНИЕ / ИСТОЧНИКИ ПРОГНОЗОВ</span><h2 id="admin-title">Подключение и настройки</h2><p>{isDemoMode?'Локальная демонстрация. Внешние модели не подключаются.':'Состояние подключённого сервиса и параметры расчёта.'}</p></div><button disabled={loading||busy} onClick={()=>void load()}>{loading?'Загрузка…':'Обновить список и аудит'}</button></div>
 {loadError&&<p className="ac-error" role="alert">{loadError} <button onClick={()=>void load()}>Повторить загрузку</button></p>}{saveError&&<p className="ac-error" role="alert">{saveError}</p>}{notice&&<p className="ac-notice" role="status">{notice}</p>}
 <dl className="ac-metrics"><div><dt>Текущий режим</dt><dd>{modes[status.mode]??status.mode??'Нет данных'}</dd></div><div><dt>Доля резервных расчётов, %</dt><dd>{isDemoMode?'Не измеряется':metric(status.fallback_ratio,100,1)}</dd></div><div><dt>Последний вызов, с</dt><dd>{isDemoMode?'Не измеряется':metric(status.latency_seconds)}</dd></div></dl>
 {user.role==='admin'&&<div className="ac-settings"><form onSubmit={e=>{e.preventDefault();if(isDemoMode)return;void save(()=>api('/settings',{ml_mode:mode},'PUT'),'Режим сохранён.')}}><h3>Режим расчёта</h3><label>Выбранный режим<select value={mode} disabled={busy||isDemoMode} onChange={e=>{dirty.current=true;setMode(e.target.value)}} required><option value="" disabled>Выберите режим</option>{Object.entries(modes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><p>{isDemoMode?'Демо использует только синтетические правила. Переключение доступно на подключённом стенде.':'Выбор применяется после сохранения. Наличие режима в списке не подтверждает доступность провайдера.'}</p><button disabled={busy||isDemoMode||!mode}>Применить режим</button></form><form onSubmit={e=>{e.preventDefault();saveThresholds()}}><h3>Пороги риска</h3><p>Значения от 0 до 1 в возрастающем порядке.</p><div className="ac-thresholds">{['low','medium','high'].map(k=><label key={k}>{riskNames[k]}<input required type="number" min="0" max="1" step="0.01" disabled={busy} value={thresholds[k]} onChange={e=>{dirty.current=true;setThresholds({...thresholds,[k]:e.target.value})}}/></label>)}</div><button disabled={busy}>{busy?'Сохранение…':'Сохранить пороги'}</button></form></div>}
 <section className="ac-section"><h3>Модели и провайдеры</h3>{loading?<p role="status">Загружаем список…</p>:loadError?<p>Список не обновлён. Повторите загрузку выше.</p>:models.length?models.map(m=><article className="ac-model" key={`${m.id}:${m.version}`}><div><h4>{m.id??'Без названия'}{m.version?` · ${m.version}`:''}</h4><p>{m.kind==='rules'?'Правила':m.kind==='stub'?'STUB':m.kind??'Тип не указан'} · {m.status??'Статус не передан'}</p></div>{m.kind!=='rules'&&<div className="ac-actions"><button disabled={busy||isDemoMode} onClick={()=>void save(()=>api('/ml/models/'+m.id+'@'+m.version+'/activate',{}),'Модель активирована.')}>Активировать</button><button disabled={busy||isDemoMode} onClick={()=>void save(()=>api('/ml/models/'+m.id+'@'+m.version+'/shadow',{}),'Теневой режим сохранён.')}>Теневой режим</button></div>}</article>):<p>Сервис не вернул зарегистрированных моделей.</p>}</section>
 {user.role==='admin'&&<section className="ac-section"><h3>Журнал действий</h3><p>До 30 последних загруженных записей. Технический путь помогает найти выполненный запрос.</p>{loading?<p role="status">Загружаем журнал…</p>:loadError?<p>Журнал не обновлён. Повторите загрузку выше.</p>:audit.length?<div className="table-scroll"><table><thead><tr><th>Время</th><th>Пользователь</th><th>Запрос</th><th>Ответ</th></tr></thead><tbody>{audit.slice(0,30).map(a=><tr key={a.id}><td>{a.ts&&Number.isFinite(Date.parse(a.ts))?date(a.ts):'Не передано'}</td><td>{a.username??'Не указан'}</td><td>{a.method} {a.path}</td><td>{a.status??'Не передан'}</td></tr>)}</tbody></table></div>:<p>В загруженном журнале нет записей.</p>}</section>}
 </section>;
}
