import {lazy, Suspense, useEffect, useMemo, useState} from 'react';
import {Activity, ArrowRight, ArrowUpRight, Camera, ChevronDown, Flame, Search, SlidersHorizontal, Waves, X} from 'lucide-react';
import {Row, date, incidentNames, isDemoMode, riskNames} from './api';
import {CriticalAlert} from './CriticalAlert';
import {useModalFocus} from './useModalFocus';
import './approved-dispatch.css';
const MapView = lazy(() => import('./MapView'));
type Props = {objects:Row[]; predictions:Row[]; events:Row[]; recommendations:Row[]; objectName:(id:string)=>string; onSelect:(p:Row)=>void; onTab:(tab:string)=>void; onDemo:(type:'fire'|'flood'|'ml-channel')=>void; canDecide:boolean; busy:boolean; criticalSignal?:Row|null; onCriticalDismiss?:()=>void};
export function Dashboard({objects,predictions,events,objectName,onSelect,onTab,onDemo,canDecide,busy,criticalSignal,onCriticalDismiss}:Props){
 const [selectedId,setSelectedId]=useState<string|null>(null),[closed,setClosed]=useState(false),[query,setQuery]=useState(''),[risk,setRisk]=useState('all'),[listOpen,setListOpen]=useState(false),[cameraOpen,setCameraOpen]=useState(false),[previewSignal,setPreviewSignal]=useState<Row|null>(null);
 const ordered=useMemo(()=>predictions.filter(p=>p.incident_type!=='intrusion_false_alarm').sort((a,b)=>(b.probability??-1)-(a.probability??-1)),[predictions]);
 const pending=ordered.filter(p=>!p.decision&&['high','medium','insufficient'].includes(p.risk));
 const selected=closed?null:ordered.find(p=>p.id===selectedId)??pending[0]??ordered[0]??null;
 const visible=ordered.filter(p=>(risk==='all'||p.risk===risk)&&objectName(p.object_id).toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru')));
 const latest=selected?events.find(e=>e.object_id===selected.object_id):null,activeAlert=criticalSignal??previewSignal;
 useEffect(()=>setCameraOpen(false),[selected?.id]);
 useEffect(()=>{if(activeAlert)setCameraOpen(false)},[activeAlert]);
 useModalFocus(cameraOpen,'.ad-camera-overlay [role="dialog"]');
 function choose(p:Row){setSelectedId(p.id);setClosed(false);setListOpen(false)}
 function dismiss(){setPreviewSignal(null);onCriticalDismiss?.()}
 const source=selected?.model_kind==='rules'?'Правила · демо':selected?.model_kind==='stub'?'STUB · демо':selected?.model_kind==='ml'?`ML · ${selected.model_id}`:'Источник не указан';
 return <div className="approved-dispatch" onKeyDown={e=>{if(e.key==='Escape'){if(cameraOpen)setCameraOpen(false);else if(listOpen)setListOpen(false);else setClosed(true)}}}>
  <div className="ad-toolbar"><button className="ad-location" onClick={()=>setListOpen(!listOpen)} aria-expanded={listOpen}>МОСКВА <span>/</span> ВСЕ УЧАСТКИ <ChevronDown size={17}/></button><label className="ad-search"><Search size={21}/><input aria-label="Поиск по участкам" placeholder="Поиск по участкам, объектам…" value={query} onChange={e=>{setQuery(e.target.value);setListOpen(true)}}/></label><button className="ad-signal-filter" onClick={()=>setListOpen(!listOpen)} aria-expanded={listOpen}><SlidersHorizontal size={18}/> Сигналы <span>{pending.length}</span></button></div>
  <div className={'ad-workspace'+(selected?' has-detail':'')}>
   <section className="ad-map" aria-label="Карта коллекторов Москвы"><Suspense fallback={<p role="status">Загружаем карту Москвы…</p>}><MapView objects={objects} predictions={predictions} selectedId={selected?.id} onFocus={choose} onSelect={onSelect} large/></Suspense></section>
   {listOpen&&<aside className="ad-list" aria-label="Поиск и фильтр сигналов"><div className="ad-panel-top"><h2>Сигналы <small>{visible.length}</small></h2><button aria-label="Закрыть список" onClick={()=>setListOpen(false)}><X/></button></div><label className="ad-risk-label">Уровень риска<select value={risk} onChange={e=>setRisk(e.target.value)}><option value="all">Все уровни</option><option value="high">Высокий</option><option value="medium">Повышенный</option><option value="low">Низкий</option><option value="insufficient">Недостаточно данных</option></select></label>{visible.map(p=><button className="ad-list-row" key={p.id} onClick={()=>choose(p)}><span className={'ad-dot '+p.risk}/><span><strong>{objectName(p.object_id)}</strong><small>{incidentNames[p.incident_type]??p.incident_type}</small></span><ArrowUpRight size={17}/></button>)}{!visible.length&&<p className="ad-empty">По этому запросу сигналов нет.</p>}</aside>}
   {selected&&<aside className="ad-inspector" aria-label={'Участок: '+objectName(selected.object_id)}><div className="ad-panel-top"><span>МОСКВА / ВЫБРАННЫЙ ОБЪЕКТ</span><button aria-label="Закрыть участок" onClick={()=>setClosed(true)}><X size={22}/></button></div><div className="ad-inspector-body"><h2>{objectName(selected.object_id)}</h2><span className={'ad-risk '+selected.risk}><span aria-hidden="true">!</span>{selected.decision?'Решение сохранено':selected.risk==='insufficient'?'Недостаточно данных':'Нужна проверка'}</span><p className="ad-description">{incidentNames[selected.incident_type]??'Риск инцидента'} <span>· прогноз на {selected.horizon_h??24} ч</span></p><button className="ad-camera" onClick={()=>setCameraOpen(true)} aria-label="Развернуть демонстрацию камеры"><img src="/collector-tunnel.webp" alt="Демонстрационная иллюстрация подземного коллектора"/><span><Camera size={15}/> КАМЕРА / СИМУЛЯЦИЯ <ArrowUpRight size={19}/></span></button><dl className="ad-facts"><div><dt>Вероятность</dt><dd>{selected.probability==null?'Нет оценки':`${Math.round(selected.probability*100)}%`}</dd><small>{riskNames[selected.risk]}</small></div><div><dt>Источник</dt><dd className="ad-text-value">{source}</dd></div><div><dt>Расчёт</dt><dd className="ad-text-value">{selected.as_of?date(selected.as_of):'Время не указано'}</dd></div></dl><div className="ad-context"><span className="ad-context-mark">ОДС</span><div><small>Последнее событие объекта</small><p>{latest?`${latest.event} · ${date(latest.ts)}`:'События по этому объекту не загружены.'}</p><button className="ad-text-link" onClick={()=>onTab('events')}>Журнал событий</button></div></div><p className="ad-data-note">Камера и положение объектов демонстрационные. Прогноз не означает подтверждённую аварию.</p></div><button className="ad-open-check" onClick={()=>onSelect(selected)}>{canDecide?'Открыть проверку':'Открыть показания'}<ArrowRight size={28}/></button></aside>}
  </div>
  {canDecide&&<details className="ad-demo-tools"><summary>Демонстрационные сценарии</summary><button disabled={busy} onClick={()=>onDemo('fire')}><Flame size={16}/> Пожар</button><button disabled={busy} onClick={()=>onDemo('flood')}><Waves size={16}/> Подтопление</button>{!isDemoMode&&<button disabled={busy} onClick={()=>onDemo('ml-channel')}><Activity size={16}/> ML: новая тревога · синтетика</button>}<button disabled={!pending.some(p=>p.risk==='high')} onClick={()=>setPreviewSignal(pending.find(p=>p.risk==='high')??null)}>Показать критический сигнал</button></details>}
  {cameraOpen&&<div className="ad-camera-overlay" onClick={()=>setCameraOpen(false)}><section role="dialog" aria-modal="true" aria-label="Демонстрация камеры" onClick={e=>e.stopPropagation()}><div className="ad-panel-top"><span>КАМЕРА / {selected?objectName(selected.object_id):'ДЕМО'}</span><button autoFocus aria-label="Закрыть демонстрацию камеры" onClick={()=>setCameraOpen(false)}><X/></button></div><img src="/collector-tunnel.webp" alt="Иллюстрация тоннеля, не реальная трансляция"/><p>Симуляция. Видеопоток заказчика не подключён.</p></section></div>}
  {activeAlert&&<CriticalAlert prediction={activeAlert} objectName={objectName(activeAlert.object_id)} preview={!criticalSignal} onOpen={()=>{choose(activeAlert);dismiss()}} onLater={dismiss}/>}
 </div>
}
