import type {Row} from './api';

// Explicit isolated frontend fixture. Never intercepts the production application.
const KEY = 'moscollector-ui-demo-v1';
const ROLES = ['dispatcher','technician','manager','analyst','admin'];
const stamp = () => new Date().toISOString();
const at = (hours: number) => new Date(Date.now() + hours * 3600000).toISOString();
const id = () => crypto.randomUUID();
type DemoState = {version:1; user:Row|null; objects:Row[]; predictions:Row[]; events:Row[]; recommendations:Row[]; notifications:Row[]; settings:Row; audit:Row[]};

function seed(): DemoState {
  const places: [string,number,number][] = [['Пресня · участок 14',55.764,37.584],['Даниловский · участок 07',55.715,37.662],['Басманный · участок 03',55.777,37.675],['Хамовники · участок 11',55.725,37.555],['Лефортово · участок 09',55.762,37.697],['Сокол · участок 02',55.793,37.576],['Дорогомилово · участок 06',55.744,37.536],['Замоскворечье · участок 05',55.726,37.622],['Таганский · участок 08',55.726,37.687],['Арбат · участок 01',55.752,37.604],['Сокольники · участок 12',55.789,37.68]];
  const objects = places.map(([name,lat,lon],i)=>({id:`obj-${String(i+1).padStart(6,'0')}`,name,lat,lon,tag:`ДЕМО-${i+1}`,synthetic:true}));
  const predictions = objects.map((o,i)=>({id:`demo-p-${i+1}`,object_id:o.id,incident_type:i===0?'fire':i===1?'flood':i===3?'intrusion_false_alarm':'sensor_failure',probability:i<3?[.68,.57,.43][i]:.18+i*.025,risk:i<3?'medium':'low',as_of:at(-.2),horizon_h:24,model_kind:'rules',model_id:'demo-rules',model_version:'1.0',role:'active',synthetic:true,decision:null,decisions:[],explanation:{top_factors:[{feature:i===1?'Уровень воды (демо)':'Изменение температуры (демо)',value:i===0?68:i===1?120:24,contribution:.21},{feature:'Сработка канала (демо)',value:1,contribution:.12}]}}));
  const events = objects.flatMap((o,i)=>[0,1,2].map((j)=>({id:`demo-e-${i}-${j}`,object_id:o.id,channel_id:100+i,ts:at(-.2-j*.3-i*.02),event:i===0?'Температура 68 °C · демонстрация':i===1?'Уровень воды 120 мм · демонстрация':'Контрольный опрос · демонстрация',severity:i<2?'warning':'info',expected:i===2&&j===1,synthetic:true}))).sort((a,b)=>b.ts.localeCompare(a.ts));
  const recommendations = objects.slice(0,4).map((o,i)=>({id:`demo-r-${i+1}`,kind:'recommendation',object_id:o.id,ts:at(-.2),data:{priority:4-i,status:i===2?'completed':i===1?'accepted':'new',action:['Сверить сигнал температуры и проверить канал','Уточнить показания уровня воды','Проверить связь с датчиком','Сверить сработку с планом работ'][i],window_from:at(i+1),window_to:at(i+3),schedule_comparison:'Демонстрационная рекомендация; допуск и регламент проверяются отдельно',rationale:{probability:predictions[i].probability},work_notes:[{author:'dispatcher',ts:at(-.3),text:'Демонстрационная запись. Перед началом уточнить состояние участка и допуск.'}]}}));
  const notifications = predictions.slice(0,3).map((p,i)=>({id:`demo-n-${i+1}`,kind:'notification',object_id:p.object_id,ts:at(-.2-i*.1),data:{prediction_id:p.id,incident_type:p.incident_type,probability:p.probability,risk:p.risk,read_by:[]}}));
  return {version:1,user:null,objects,predictions,events,recommendations,notifications,audit:[],settings:{ml_mode:'rules',risk_thresholds:{low:.2,medium:.4,high:.8},horizons_h:[24],maintenance_note:'Синтетические рекомендации для проверки интерфейса. Не являются нарядом или допуском.',reasons:{reasons:{confirmed_signals:'Подтверждено сопутствующими сигналами',planned_work:'Плановые работы',sensor_fault:'Неисправность датчика',weather:'Метеоусловия',visual_check:'Визуальная проверка',insufficient_data:'Недостаточно данных',animal:'Животные / помехи'}}}};
}
function read():DemoState {try {const saved=JSON.parse(localStorage.getItem(KEY)??'null');if(saved?.version===1&&Array.isArray(saved.predictions))return saved;} catch {/* Broken fixture resets only this namespace. */} return seed();}
function persist(state:DemoState){localStorage.setItem(KEY,JSON.stringify(state));}
function find(rows:Row[],identity:string){const row=rows.find(r=>r.id===identity);if(!row)throw new Error('Демонстрационная запись не найдена');return row;}
function permit(state:DemoState,...roles:string[]){if(!state.user||(!roles.includes(state.user.role)&&state.user.role!=='admin'))throw new Error('Действие недоступно для этой роли');}
function page(rows:Row[],params:URLSearchParams){const offset=Math.max(0,Number(params.get('offset')??0)),limit=Math.max(1,Number(params.get('limit')??1000));return {items:rows.slice(offset,offset+limit),total:rows.length,limit,offset};}

export async function demoApi(path:string,body?:unknown,method?:string):Promise<any>{
 const url=new URL(path,'http://demo.local'),route=url.pathname,verb=method??(body===undefined?'GET':'POST'),payload=(body??{}) as Row,state=read();
 const save=(result:unknown)=>{state.audit.unshift({id:id(),ts:stamp(),username:state.user?.username??'demo',method:verb,path:route,status:200});persist(state);return structuredClone(result);};
 if(route==='/auth/login'&&verb==='POST'){const role=String(payload.username??'').trim();if(!ROLES.includes(role)||payload.password!=='demo')throw new Error('Демо-вход: dispatcher, technician, manager, analyst или admin; пароль demo');state.user={username:role,role,demo:true};return save({user:state.user});}
 if(route==='/auth/logout'&&verb==='POST'){state.user=null;return save({ok:true});}
 if(!state.user)throw new Error('Войдите в демонстрационный режим');
 if(route==='/auth/me'&&verb==='GET')return state.user;
 if(route==='/objects'&&verb==='GET')return page(state.objects,url.searchParams);
 if(route.startsWith('/objects/')&&verb==='GET'){const object=find(state.objects,route.split('/')[2]);return {...object,context:{synthetic:true,planned_works:[],channels:[{channel_id:101,type_code:'temperature',health:{status:'ok',reasons:[]},series:{points:Array.from({length:24},(_,i)=>[at(i-24),object.id==='obj-000001'?25+i*1.87:23+Math.sin(i)*2])}},{channel_id:201,type_code:'water_level',health:{status:'ok',reasons:[]},series:{points:Array.from({length:24},(_,i)=>[at(i-24),80+i])}}]}};}
 if(route==='/events'&&verb==='GET'){let rows=state.events.filter(e=>(!url.searchParams.get('object_id')||e.object_id===url.searchParams.get('object_id'))&&(!url.searchParams.get('start')||e.ts>=url.searchParams.get('start')!)&&(!url.searchParams.get('end')||e.ts<=url.searchParams.get('end')!));rows.sort((a,b)=>url.searchParams.get('sort')==='asc'?a.ts.localeCompare(b.ts):b.ts.localeCompare(a.ts));return page(rows,url.searchParams);}
 if(route==='/predictions'&&verb==='GET'){let rows=state.predictions.filter(p=>['object_id','incident_type','risk'].every(k=>!url.searchParams.get(k)||p[k]===url.searchParams.get(k)));if(url.searchParams.get('latest')==='true'){const seen=new Set<string>();rows=[...rows].sort((a,b)=>b.as_of.localeCompare(a.as_of)).filter(p=>{const key=`${p.object_id}:${p.incident_type}`;if(seen.has(key))return false;seen.add(key);return true})}return page(rows,url.searchParams);}
 if(route==='/predictions/run'&&verb==='POST'){permit(state,'dispatcher','analyst');state.predictions.forEach(p=>{p.as_of=stamp()});return save({items:state.predictions,synthetic:true});}
 if(route==='/predictions/what-if'&&verb==='POST'){permit(state,'dispatcher','analyst');return {synthetic:true,predictions:(payload.object_ids??[]).map((object_id:string)=>({object_id,incident_type:'flood',probability:Math.min(.95,.25+Math.max(0,Number(payload.precip_mm_delta))*0.01),model_kind:'rules'}))};}
 if(/^\/predictions\/[^/]+\/analogs$/.test(route)&&verb==='GET'){find(state.predictions,route.split('/')[2]);return {items:[],method:'В демонстрации исторические аналоги не загружены'};}
 if(/^\/predictions\/[^/]+\/decision$/.test(route)&&verb==='POST'){permit(state,'dispatcher','analyst');const p=find(state.predictions,route.split('/')[2]);if(!['inspect','dispatch','monitor','false_alarm'].includes(payload.action)||!['confirmed','false','monitoring'].includes(payload.outcome)||!state.settings.reasons.reasons[payload.reason]||String(payload.comment??'').trim().length<3)throw new Error('Заполните действие, причину и комментарий');const decision={...payload,id:id(),prediction_id:p.id,username:state.user.username,ts:stamp(),synthetic:true};p.decision=decision;p.decisions.push(decision);state.events.unshift({id:id(),object_id:p.object_id,channel_id:'—',ts:stamp(),event:`Демо-решение ${payload.action}: ${payload.comment}`,severity:'info',expected:false});return save(decision);}
 if(/^\/predictions\/[^/]+$/.test(route)&&verb==='GET')return find(state.predictions,route.split('/')[2]);
 if(route==='/recommendations'&&verb==='GET')return page(state.recommendations,url.searchParams);
 if(/^\/recommendations\/[^/]+/.test(route)){const r=find(state.recommendations,route.split('/')[2]);if(route.endsWith('/draft-order')&&verb==='POST'){permit(state,'dispatcher');return {draft:true,sent:false,synthetic:true,object_id:r.object_id,...r.data};}permit(state,'dispatcher','technician');if(route.endsWith('/notes')&&verb==='POST'){const text=String(payload.text??'').trim();if(text.length<3||text.length>1000)throw new Error('Комментарий: от 3 до 1000 символов');r.data.work_notes.push({author:state.user.username,text,ts:stamp()});return save(r);}if(verb==='PATCH'){if(!['accepted','rejected','completed'].includes(payload.status))throw new Error('Недопустимый статус');if(payload.status==='rejected'&&!payload.reason)throw new Error('Укажите причину отклонения');r.data={...r.data,status:payload.status,updated_by:state.user.username};return save(r);}}
 if(route==='/settings'&&verb==='GET')return state.settings;
 if(route==='/settings'&&verb==='PUT'){permit(state,'admin');if(payload.ml_mode&&payload.ml_mode!=='rules')throw new Error('В демонстрации доступен только синтетический режим rules. Подключение модели не имитируется.');if(payload.risk_thresholds){const t=payload.risk_thresholds;if(!(0<=t.low&&t.low<t.medium&&t.medium<t.high&&t.high<=1))throw new Error('Пороги должны возрастать от 0 до 1');}state.settings={...state.settings,...payload};return save(state.settings);}
 if(route==='/ml/status'&&verb==='GET')return {mode:'rules',degraded:false,synthetic:true,fallback_ratio:0,latency_seconds:0};
 if(route==='/ml/models'&&verb==='GET'){permit(state,'analyst');return [{id:'demo-rules',version:'1.0',kind:'rules',status:'Синтетический пример; модель не подключена'}];}
 if(route==='/notifications'&&verb==='GET')return page(state.notifications,url.searchParams);
 if(/^\/notifications\/[^/]+\/read$/.test(route)&&verb==='POST'){const n=find(state.notifications,route.split('/')[2]);n.data.read_by=[...new Set([...n.data.read_by,state.user.username])];return save({ok:true});}
 if(route==='/admin/audit'&&verb==='GET'){permit(state,'admin');return page(state.audit,url.searchParams);}
 if(route==='/admin/users'&&verb==='GET'){permit(state,'admin');return ROLES.map(role=>({username:role,role,telegram_linked:false,telegram_enabled:false,telegram_chat_id:null}));}
 if(route==='/telegram/status'&&verb==='GET')return {linked:false,enabled:false,chat_id:null};
 if(route.startsWith('/evaluation/')&&verb==='GET'){permit(state,'manager','analyst');if(route==='/evaluation/model-comparison')return [];if(route==='/evaluation/metrics')return {count:0,series:[],synthetic:true};}
 if(/^\/demo\/(fire|flood)$/.test(route)&&verb==='POST'){permit(state,'dispatcher','analyst');const incident=route.split('/')[2],previous=state.predictions.find(p=>p.incident_type===incident)!;const p:Row={...structuredClone(previous),id:id(),risk:'high',probability:.91,as_of:stamp(),decision:null,decisions:[]};state.predictions.unshift(p);const notification={id:id(),kind:'notification',object_id:p.object_id,ts:stamp(),data:{prediction_id:p.id,incident_type:p.incident_type,probability:p.probability,risk:'high',read_by:[]}};state.notifications.unshift(notification);state.events.unshift({id:id(),object_id:p.object_id,channel_id:'—',ts:stamp(),event:`Демонстрационный прогноз: ${incident==='fire'?'риск пожара':'риск подтопления'}`,severity:'warning',expected:false});const result=save({items:[p],prediction:p,synthetic:true});window.dispatchEvent(new CustomEvent('moscollector-demo-notification',{detail:notification}));return result;}
 if(route==='/notification-delivery/status'&&verb==='GET'){permit(state,'admin');return {channels:['telegram','email','sms'].map(channel=>({channel,state:'disabled'}))};}
 if(route==='/notification-delivery/outbox'&&verb==='GET'){permit(state,'admin');return {items:[]};}
 throw new Error(`В локальном демо действие ${verb} ${route} не подключено. Используйте основной стенд для реальной интеграции.`);
}
