import React from 'react';
import ReactDOM from 'react-dom/client';
import 'leaflet/dist/leaflet.css';
import './style.css';
import './atlas.css';
import './forum.css';
import './editorial.css';
import './dispatch.css';
import './workplace.css';
import './control-room.css';
import './reference-direction.css';
import './approved-shell.css';
import './role-workspaces.css';
import './role-approved.css';
import './approved-dispatch.css';
import App from './App';
import './reference-system.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
